# Generated by Django 6.0.6 on 2026-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_business_name_user_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('NGO', 'NGO'), ('DELIVERY', 'Delivery Partner'), ('ADMIN', 'Admin')], default='BUSINESS', max_length=20),
        ),
    ]
