# Generated by Django 6.0.6 on 2026-07-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_current_latitude_user_current_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('NGO', 'NGO'), ('DELIVERY', 'Delivery Partner'), ('ADMIN', 'Admin'), ('INDIVIDUAL', 'Individual Donor')], default='BUSINESS', max_length=20),
        ),
    ]
