# Generated by Django 6.0.6 on 2026-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Restaurant', 'Restaurant'), ('Supermarket', 'Supermarket'), ('Bakery', 'Bakery'), ('Cafe', 'Cafe'), ('Hotel', 'Hotel'), ('Cloud Kitchen', 'Cloud Kitchen')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
