# Generated by Django 6.0.6 on 2026-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_vehicle_number_user_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
