# Generated by Django 6.0.6 on 2026-07-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='business',
        ),
    ]
