# Generated by Django 6.0.6 on 2026-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_barcode_inventory_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='recommended_vehicle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
