# Generated by Django 6.0.6 on 2026-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_recommended_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='delivery_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='inventory',
            name='delivery_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pickup_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pickup_verified',
            field=models.BooleanField(default=False),
        ),
    ]
