# Generated by Django 6.0.6 on 2026-07-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Donated', 'Donated'), ('Accepted', 'Accepted'), ('Scheduled', 'Scheduled'), ('Out For Pickup', 'Out For Pickup'), ('Delivered', 'Delivered'), ('Expired', 'Expired')], default='Available', max_length=20),
        ),
    ]
