# Generated by Django 6.0.6 on 2026-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
