# Generated by Django 6.0.6 on 2026-07-04 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Dairy', 'Dairy'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Bakery', 'Bakery'), ('Beverages', 'Beverages'), ('Others', 'Others')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('Litre', 'Litre'), ('Packet', 'Packet'), ('Piece', 'Piece')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('storage_type', models.CharField(choices=[('Room Temperature', 'Room Temperature'), ('Refrigerated', 'Refrigerated'), ('Frozen', 'Frozen')], max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Donated', 'Donated'), ('Expired', 'Expired')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
