# Generated by Django 6.0.6 on 2026-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Donated', 'Donated'), ('Accepted', 'Accepted'), ('Expired', 'Expired')], default='Available', max_length=20),
        ),
    ]
