# Generated by Django 6.0.6 on 2026-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='volunteer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
