# Generated by Django 6.0.6 on 2026-07-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_pickup_date_inventory_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
