# Generated by Django 6.0.6 on 2026-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='donor_type',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('INDIVIDUAL', 'Individual')], default='BUSINESS', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='pickup_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
